# Generated by Django 5.1.15 on 2026-08-29 09:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'duos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='authentication.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='authentication.profile')),
            ],
            options={
                'db_table': 'connection_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'status'], name='connection__sender__6f537e_idx'), models.Index(fields=['receiver', 'status'], name='connection__receive_25181a_idx')],
            },
        ),
        migrations.CreateModel(
            name='DuoMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(default='MEMBER', max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('duo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='duos.duo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duo_memberships', to='authentication.profile')),
            ],
            options={
                'db_table': 'duo_members',
                'ordering': ['joined_at'],
                'unique_together': {('duo', 'user')},
            },
        ),
    ]
