# Generated by Django 5.1.15 on 2026-09-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duos', '0002_pairingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='duo',
            name='disappearing_mode',
            field=models.BooleanField(default=False),
        ),
    ]
