# Generated by Django 5.1.15 on 2026-08-29 09:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CONNECTION_REQUEST', 'Connection Request'), ('CONNECTION_ACCEPTED', 'Connection Accepted'), ('MESSAGE', 'New Message'), ('DRAWING', 'New Drawing'), ('DAILY_RESPONSE', 'Daily Response Submitted')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='authentication.profile')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_dde14f_idx')],
            },
        ),
    ]
