# Generated by Django 5.1.15 on 2026-08-29 09:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_user_id', models.UUIDField(db_index=True, unique=True)),
                ('name', models.CharField(default='DUO Member', max_length=150)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('avatar_url', models.TextField(blank=True, default='')),
                ('duo_code', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
