# Generated by Django 5.1.15 on 2026-08-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enter_to_send',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='read_receipts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(default='system', max_length=20),
        ),
    ]
