# Generated by Django 5.1.15 on 2026-09-01 05:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_profile_enter_to_send_profile_notifications_enabled_and_more'),
        ('duos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('emoji', models.CharField(default='📌', max_length=20)),
                ('color', models.CharField(default='#FAF7F2', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_categories', to='duos.duo')),
            ],
            options={
                'db_table': 'todo_categories',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='todos.todocategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_todos', to='authentication.profile')),
                ('duo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_items', to='duos.duo')),
            ],
            options={
                'db_table': 'todo_items',
                'ordering': ['is_completed', 'order', '-created_at'],
            },
        ),
    ]
