# Generated by Django 5.1.15 on 2026-09-01 06:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_enter_to_send_profile_notifications_enabled_and_more'),
        ('duos', '0001_initial'),
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='duo',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='TODO', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='authentication.profile')),
                ('duo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='duos.duo')),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TodoCategory',
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
