# Generated by Django 5.1.15 on 2026-09-01 05:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_profile_enter_to_send_profile_notifications_enabled_and_more'),
        ('duos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('TEXT', 'Text Note'), ('PHOTO', 'Photo Note'), ('VOICE', 'Voice Note'), ('DRAWING', 'Drawing Note')], default='TEXT', max_length=20)),
                ('content', models.TextField(blank=True, default='')),
                ('media_url', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='#FAF7F2', max_length=30)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='authentication.profile')),
                ('duo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='duos.duo')),
            ],
            options={
                'db_table': 'little_notes',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
