# Generated by Django 5.1.15 on 2026-08-29 09:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('duos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_path', models.CharField(max_length=500)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='duos.duo')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_drawings', to='authentication.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_drawings', to='authentication.profile')),
            ],
            options={
                'db_table': 'drawings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['duo', '-created_at'], name='drawings_duo_id_debfa7_idx')],
            },
        ),
    ]
