# Generated by Django 5.1.15 on 2026-08-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='storage_path',
            field=models.TextField(),
        ),
    ]
