# Generated by Django 5.1.15 on 2026-08-29 09:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('duos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='duos.duo')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='authentication.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='authentication.profile')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['duo', 'created_at'], name='messages_duo_id_1b77a9_idx'), models.Index(fields=['receiver', 'read_at'], name='messages_receive_d8f769_idx')],
            },
        ),
    ]
