# Generated by Django 5.1.15 on 2026-09-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_enter_to_send_profile_notifications_enabled_and_more'),
        ('chat', '0002_message_is_unsent_message_reactions_message_reply_to'),
        ('duos', '0003_duo_disappearing_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_disappearing',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['duo', 'is_disappearing', 'expires_at'], name='messages_duo_id_ce2495_idx'),
        ),
    ]
