# Generated by Django 5.1.15 on 2026-08-29 09:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('duos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('category', models.CharField(blank=True, default='DAILY', max_length=50)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.TextField(blank=True, default='')),
                ('response_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], db_index=True, default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_responses', to='duos.duo')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='daily.dailyquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_responses', to='authentication.profile')),
            ],
            options={
                'db_table': 'daily_responses',
                'ordering': ['response_date', 'question__order'],
                'indexes': [models.Index(fields=['duo', 'response_date', 'status'], name='daily_respo_duo_id_39ac1e_idx'), models.Index(fields=['user', 'response_date', 'status'], name='daily_respo_user_id_cf91c7_idx')],
                'unique_together': {('question', 'user', 'duo', 'response_date')},
            },
        ),
    ]
