# Generated by Django 5.1.15 on 2026-09-01 10:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_enter_to_send_profile_notifications_enabled_and_more'),
        ('daily', '0001_initial'),
        ('duos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquestion',
            name='genre',
            field=models.CharField(choices=[('FUN', 'Fun / Playful'), ('DEEP', 'Deep / Emotional'), ('IMAGINATIVE', 'Imaginative / Hypothetical')], db_index=True, default='FUN', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyquestion',
            name='question',
            field=models.TextField(unique=True),
        ),
        migrations.CreateModel(
            name='DailyPromptAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('genre', models.CharField(choices=[('FUN', 'Fun / Playful'), ('DEEP', 'Deep / Emotional'), ('IMAGINATIVE', 'Imaginative / Hypothetical')], db_index=True, max_length=20)),
                ('assigned_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('CARRIED_FORWARD', 'Carried Forward'), ('REPLACED', 'Replaced'), ('ANSWERED', 'Answered')], db_index=True, default='ASSIGNED', max_length=20)),
                ('is_carried_forward', models.BooleanField(default=False)),
                ('original_assigned_date', models.DateField(blank=True, null=True)),
                ('replaced_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_assignments', to='duos.duo')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_prompt_assignments', to='authentication.profile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='daily.dailyquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_assignments', to='authentication.profile')),
            ],
            options={
                'db_table': 'daily_prompt_assignments',
                'ordering': ['assigned_date', 'genre', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='dailyresponse',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='daily.dailypromptassignment'),
        ),
        migrations.AddIndex(
            model_name='dailypromptassignment',
            index=models.Index(fields=['user', 'assigned_date', 'status'], name='daily_promp_user_id_321ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='dailypromptassignment',
            index=models.Index(fields=['duo', 'assigned_date'], name='daily_promp_duo_id_25503d_idx'),
        ),
        migrations.AddIndex(
            model_name='dailypromptassignment',
            index=models.Index(fields=['question', 'status'], name='daily_promp_questio_0b60c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailypromptassignment',
            unique_together={('user', 'question', 'assigned_date')},
        ),
    ]
